/*
 * This file is part of JEngine.
 *
 * Copyright (C) 2013 Victor Burlakov
 *
 * JEngine is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * JEngine is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with JEngine.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.jenginetest.builder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the WLEntry service. Represents a row in the &quot;WL_WLEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.jenginetest.builder.model.impl.WLEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.jenginetest.builder.model.impl.WLEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see WLEntry
 * @see com.jenginetest.builder.model.impl.WLEntryImpl
 * @see com.jenginetest.builder.model.impl.WLEntryModelImpl
 * @generated
 */
public interface WLEntryModel extends BaseModel<WLEntry> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a w l entry model instance should use the {@link WLEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this w l entry.
	 *
	 * @return the primary key of this w l entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this w l entry.
	 *
	 * @param primaryKey the primary key of this w l entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the entry ID of this w l entry.
	 *
	 * @return the entry ID of this w l entry
	 */
	public long getEntryId();

	/**
	 * Sets the entry ID of this w l entry.
	 *
	 * @param entryId the entry ID of this w l entry
	 */
	public void setEntryId(long entryId);

	/**
	 * Returns the create user ID of this w l entry.
	 *
	 * @return the create user ID of this w l entry
	 */
	public long getCreateUserId();

	/**
	 * Sets the create user ID of this w l entry.
	 *
	 * @param createUserId the create user ID of this w l entry
	 */
	public void setCreateUserId(long createUserId);

	/**
	 * Returns the create user uuid of this w l entry.
	 *
	 * @return the create user uuid of this w l entry
	 * @throws SystemException if a system exception occurred
	 */
	public String getCreateUserUuid() throws SystemException;

	/**
	 * Sets the create user uuid of this w l entry.
	 *
	 * @param createUserUuid the create user uuid of this w l entry
	 */
	public void setCreateUserUuid(String createUserUuid);

	/**
	 * Returns the create user name of this w l entry.
	 *
	 * @return the create user name of this w l entry
	 */
	@AutoEscape
	public String getCreateUserName();

	/**
	 * Sets the create user name of this w l entry.
	 *
	 * @param createUserName the create user name of this w l entry
	 */
	public void setCreateUserName(String createUserName);

	/**
	 * Returns the create date of this w l entry.
	 *
	 * @return the create date of this w l entry
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this w l entry.
	 *
	 * @param createDate the create date of this w l entry
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified user ID of this w l entry.
	 *
	 * @return the modified user ID of this w l entry
	 */
	public long getModifiedUserId();

	/**
	 * Sets the modified user ID of this w l entry.
	 *
	 * @param modifiedUserId the modified user ID of this w l entry
	 */
	public void setModifiedUserId(long modifiedUserId);

	/**
	 * Returns the modified user uuid of this w l entry.
	 *
	 * @return the modified user uuid of this w l entry
	 * @throws SystemException if a system exception occurred
	 */
	public String getModifiedUserUuid() throws SystemException;

	/**
	 * Sets the modified user uuid of this w l entry.
	 *
	 * @param modifiedUserUuid the modified user uuid of this w l entry
	 */
	public void setModifiedUserUuid(String modifiedUserUuid);

	/**
	 * Returns the modified user name of this w l entry.
	 *
	 * @return the modified user name of this w l entry
	 */
	@AutoEscape
	public String getModifiedUserName();

	/**
	 * Sets the modified user name of this w l entry.
	 *
	 * @param modifiedUserName the modified user name of this w l entry
	 */
	public void setModifiedUserName(String modifiedUserName);

	/**
	 * Returns the modified date of this w l entry.
	 *
	 * @return the modified date of this w l entry
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this w l entry.
	 *
	 * @param modifiedDate the modified date of this w l entry
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the start of this w l entry.
	 *
	 * @return the start of this w l entry
	 */
	public Date getStart();

	/**
	 * Sets the start of this w l entry.
	 *
	 * @param start the start of this w l entry
	 */
	public void setStart(Date start);

	/**
	 * Returns the start time of this w l entry.
	 *
	 * @return the start time of this w l entry
	 */
	public long getStartTime();

	/**
	 * Sets the start time of this w l entry.
	 *
	 * @param startTime the start time of this w l entry
	 */
	public void setStartTime(long startTime);

	/**
	 * Returns the finish time of this w l entry.
	 *
	 * @return the finish time of this w l entry
	 */
	public long getFinishTime();

	/**
	 * Sets the finish time of this w l entry.
	 *
	 * @param finishTime the finish time of this w l entry
	 */
	public void setFinishTime(long finishTime);

	/**
	 * Returns the entry date of this w l entry.
	 *
	 * @return the entry date of this w l entry
	 */
	public Date getEntryDate();

	/**
	 * Sets the entry date of this w l entry.
	 *
	 * @param entryDate the entry date of this w l entry
	 */
	public void setEntryDate(Date entryDate);

	/**
	 * Returns the entry time of this w l entry.
	 *
	 * @return the entry time of this w l entry
	 */
	public long getEntryTime();

	/**
	 * Sets the entry time of this w l entry.
	 *
	 * @param entryTime the entry time of this w l entry
	 */
	public void setEntryTime(long entryTime);

	/**
	 * Returns the timezone of this w l entry.
	 *
	 * @return the timezone of this w l entry
	 */
	public int getTimezone();

	/**
	 * Sets the timezone of this w l entry.
	 *
	 * @param timezone the timezone of this w l entry
	 */
	public void setTimezone(int timezone);

	/**
	 * Returns the length of this w l entry.
	 *
	 * @return the length of this w l entry
	 */
	public long getLength();

	/**
	 * Sets the length of this w l entry.
	 *
	 * @param length the length of this w l entry
	 */
	public void setLength(long length);

	/**
	 * Returns the task ID of this w l entry.
	 *
	 * @return the task ID of this w l entry
	 */
	public long getTaskId();

	/**
	 * Sets the task ID of this w l entry.
	 *
	 * @param taskId the task ID of this w l entry
	 */
	public void setTaskId(long taskId);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(WLEntry wlEntry);

	public int hashCode();

	public CacheModel<WLEntry> toCacheModel();

	public WLEntry toEscapedModel();

	public String toString();

	public String toXmlString();
}