/*
 * This file is part of JEngine.
 *
 * Copyright (C) 2013 Victor Burlakov
 *
 * JEngine is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * JEngine is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with JEngine.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.jenginetest.builder.model;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the WLProjectUser service. Represents a row in the &quot;WL_WLProjectUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.jenginetest.builder.model.impl.WLProjectUserModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.jenginetest.builder.model.impl.WLProjectUserImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see WLProjectUser
 * @see com.jenginetest.builder.model.impl.WLProjectUserImpl
 * @see com.jenginetest.builder.model.impl.WLProjectUserModelImpl
 * @generated
 */
public interface WLProjectUserModel extends BaseModel<WLProjectUser> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a w l project user model instance should use the {@link WLProjectUser} interface instead.
	 */

	/**
	 * Returns the primary key of this w l project user.
	 *
	 * @return the primary key of this w l project user
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this w l project user.
	 *
	 * @param primaryKey the primary key of this w l project user
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the group ID of this w l project user.
	 *
	 * @return the group ID of this w l project user
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this w l project user.
	 *
	 * @param groupId the group ID of this w l project user
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this w l project user.
	 *
	 * @return the company ID of this w l project user
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this w l project user.
	 *
	 * @param companyId the company ID of this w l project user
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the project user ID of this w l project user.
	 *
	 * @return the project user ID of this w l project user
	 */
	public long getProjectUserId();

	/**
	 * Sets the project user ID of this w l project user.
	 *
	 * @param projectUserId the project user ID of this w l project user
	 */
	public void setProjectUserId(long projectUserId);

	/**
	 * Returns the project user uuid of this w l project user.
	 *
	 * @return the project user uuid of this w l project user
	 * @throws SystemException if a system exception occurred
	 */
	public String getProjectUserUuid() throws SystemException;

	/**
	 * Sets the project user uuid of this w l project user.
	 *
	 * @param projectUserUuid the project user uuid of this w l project user
	 */
	public void setProjectUserUuid(String projectUserUuid);

	/**
	 * Returns the user ID of this w l project user.
	 *
	 * @return the user ID of this w l project user
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this w l project user.
	 *
	 * @param userId the user ID of this w l project user
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this w l project user.
	 *
	 * @return the user uuid of this w l project user
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this w l project user.
	 *
	 * @param userUuid the user uuid of this w l project user
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the project ID of this w l project user.
	 *
	 * @return the project ID of this w l project user
	 */
	public long getProjectId();

	/**
	 * Sets the project ID of this w l project user.
	 *
	 * @param projectId the project ID of this w l project user
	 */
	public void setProjectId(long projectId);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(WLProjectUser wlProjectUser);

	public int hashCode();

	public CacheModel<WLProjectUser> toCacheModel();

	public WLProjectUser toEscapedModel();

	public String toString();

	public String toXmlString();
}