package com.cetus.jengine.orm.ext.liferay.testportlet.model.impl;

import com.cetus.jengine.orm.ext.liferay.testportlet.model.SAuthor;
import com.cetus.jengine.orm.ext.liferay.testportlet.service.SAuthorLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the SAuthor service. Represents a row in the &quot;SB_SAuthor&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SAuthorImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SAuthorImpl
 * @see com.cetus.jengine.orm.ext.liferay.testportlet.model.SAuthor
 * @generated
 */
public abstract class SAuthorBaseImpl extends SAuthorModelImpl
    implements SAuthor {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a s author model instance should use the {@link SAuthor} interface instead.
     */
    public void persist() throws SystemException {
        if (this.isNew()) {
            SAuthorLocalServiceUtil.addSAuthor(this);
        } else {
            SAuthorLocalServiceUtil.updateSAuthor(this);
        }
    }
}
