package com.cetus.jengine.orm.ext.liferay.testportlet.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the SAuthor service. Represents a row in the &quot;SB_SAuthor&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.cetus.jengine.orm.ext.liferay.testportlet.model.impl.SAuthorModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.cetus.jengine.orm.ext.liferay.testportlet.model.impl.SAuthorImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SAuthor
 * @see com.cetus.jengine.orm.ext.liferay.testportlet.model.impl.SAuthorImpl
 * @see com.cetus.jengine.orm.ext.liferay.testportlet.model.impl.SAuthorModelImpl
 * @generated
 */
public interface SAuthorModel extends BaseModel<SAuthor> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a s author model instance should use the {@link SAuthor} interface instead.
     */

    /**
     * Returns the primary key of this s author.
     *
     * @return the primary key of this s author
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this s author.
     *
     * @param primaryKey the primary key of this s author
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the author ID of this s author.
     *
     * @return the author ID of this s author
     */
    public long getAuthorId();

    /**
     * Sets the author ID of this s author.
     *
     * @param authorId the author ID of this s author
     */
    public void setAuthorId(long authorId);

    /**
     * Returns the first name of this s author.
     *
     * @return the first name of this s author
     */
    @AutoEscape
    public String getFirstName();

    /**
     * Sets the first name of this s author.
     *
     * @param firstName the first name of this s author
     */
    public void setFirstName(String firstName);

    /**
     * Returns the last name of this s author.
     *
     * @return the last name of this s author
     */
    @AutoEscape
    public String getLastName();

    /**
     * Sets the last name of this s author.
     *
     * @param lastName the last name of this s author
     */
    public void setLastName(String lastName);

    public boolean isNew();

    public void setNew(boolean n);

    public boolean isCachedModel();

    public void setCachedModel(boolean cachedModel);

    public boolean isEscapedModel();

    public Serializable getPrimaryKeyObj();

    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    public ExpandoBridge getExpandoBridge();

    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    public Object clone();

    public int compareTo(SAuthor sAuthor);

    public int hashCode();

    public CacheModel<SAuthor> toCacheModel();

    public SAuthor toEscapedModel();

    public String toString();

    public String toXmlString();
}
