/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.jenginetest.builder.model.impl;

import com.jenginetest.builder.model.SAuthor;
import com.jenginetest.builder.service.SAuthorLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the SAuthor service. Represents a row in the &quot;SB_SAuthor&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SAuthorImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SAuthorImpl
 * @see com.jenginetest.builder.model.SAuthor
 * @generated
 */
public abstract class SAuthorBaseImpl extends SAuthorModelImpl
	implements SAuthor {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a s author model instance should use the {@link SAuthor} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			SAuthorLocalServiceUtil.addSAuthor(this);
		}
		else {
			SAuthorLocalServiceUtil.updateSAuthor(this);
		}
	}
}