/*
 * This file is part of JEngine.
 *
 * Copyright (C) 2013 Victor Burlakov
 *
 * JEngine is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * JEngine is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with JEngine.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.jenginetest.builder.model.impl;

import com.jenginetest.builder.model.WLProjectUserRole;
import com.jenginetest.builder.model.WLProjectUserRoleModel;
import com.jenginetest.builder.model.WLProjectUserRoleSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the WLProjectUserRole service. Represents a row in the &quot;WL_WLProjectUserRole&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.jenginetest.builder.model.WLProjectUserRoleModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link WLProjectUserRoleImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see WLProjectUserRoleImpl
 * @see com.jenginetest.builder.model.WLProjectUserRole
 * @see com.jenginetest.builder.model.WLProjectUserRoleModel
 * @generated
 */
@JSON(strict = true)
public class WLProjectUserRoleModelImpl extends BaseModelImpl<WLProjectUserRole>
	implements WLProjectUserRoleModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a w l project user role model instance should use the {@link com.jenginetest.builder.model.WLProjectUserRole} interface instead.
	 */
	public static final String TABLE_NAME = "WL_WLProjectUserRole";
	public static final Object[][] TABLE_COLUMNS = {
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "projectUserRoleId", Types.BIGINT },
			{ "projectUserId", Types.BIGINT },
			{ "roleId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table WL_WLProjectUserRole (groupId LONG,companyId LONG,projectUserRoleId LONG not null primary key,projectUserId LONG,roleId LONG)";
	public static final String TABLE_SQL_DROP = "drop table WL_WLProjectUserRole";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.jenginetest.builder.model.WLProjectUserRole"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.jenginetest.builder.model.WLProjectUserRole"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.jenginetest.builder.model.WLProjectUserRole"),
			true);
	public static long COMPANYID_COLUMN_BITMASK = 1L;
	public static long GROUPID_COLUMN_BITMASK = 2L;
	public static long PROJECTUSERID_COLUMN_BITMASK = 4L;
	public static long ROLEID_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static WLProjectUserRole toModel(WLProjectUserRoleSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		WLProjectUserRole model = new WLProjectUserRoleImpl();

		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setProjectUserRoleId(soapModel.getProjectUserRoleId());
		model.setProjectUserId(soapModel.getProjectUserId());
		model.setRoleId(soapModel.getRoleId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<WLProjectUserRole> toModels(
		WLProjectUserRoleSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<WLProjectUserRole> models = new ArrayList<WLProjectUserRole>(soapModels.length);

		for (WLProjectUserRoleSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.jenginetest.builder.model.WLProjectUserRole"));

	public WLProjectUserRoleModelImpl() {
	}

	public long getPrimaryKey() {
		return _projectUserRoleId;
	}

	public void setPrimaryKey(long primaryKey) {
		setProjectUserRoleId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_projectUserRoleId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return WLProjectUserRole.class;
	}

	public String getModelClassName() {
		return WLProjectUserRole.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("projectUserRoleId", getProjectUserRoleId());
		attributes.put("projectUserId", getProjectUserId());
		attributes.put("roleId", getRoleId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long projectUserRoleId = (Long)attributes.get("projectUserRoleId");

		if (projectUserRoleId != null) {
			setProjectUserRoleId(projectUserRoleId);
		}

		Long projectUserId = (Long)attributes.get("projectUserId");

		if (projectUserId != null) {
			setProjectUserId(projectUserId);
		}

		Long roleId = (Long)attributes.get("roleId");

		if (roleId != null) {
			setRoleId(roleId);
		}
	}

	@JSON
	public long getGroupId() {
		return _groupId;
	}

	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	public long getCompanyId() {
		return _companyId;
	}

	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	public long getProjectUserRoleId() {
		return _projectUserRoleId;
	}

	public void setProjectUserRoleId(long projectUserRoleId) {
		_projectUserRoleId = projectUserRoleId;
	}

	@JSON
	public long getProjectUserId() {
		return _projectUserId;
	}

	public void setProjectUserId(long projectUserId) {
		_columnBitmask |= PROJECTUSERID_COLUMN_BITMASK;

		if (!_setOriginalProjectUserId) {
			_setOriginalProjectUserId = true;

			_originalProjectUserId = _projectUserId;
		}

		_projectUserId = projectUserId;
	}

	public String getProjectUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getProjectUserId(), "uuid",
			_projectUserUuid);
	}

	public void setProjectUserUuid(String projectUserUuid) {
		_projectUserUuid = projectUserUuid;
	}

	public long getOriginalProjectUserId() {
		return _originalProjectUserId;
	}

	@JSON
	public long getRoleId() {
		return _roleId;
	}

	public void setRoleId(long roleId) {
		_columnBitmask |= ROLEID_COLUMN_BITMASK;

		if (!_setOriginalRoleId) {
			_setOriginalRoleId = true;

			_originalRoleId = _roleId;
		}

		_roleId = roleId;
	}

	public long getOriginalRoleId() {
		return _originalRoleId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			WLProjectUserRole.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public WLProjectUserRole toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (WLProjectUserRole)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		WLProjectUserRoleImpl wlProjectUserRoleImpl = new WLProjectUserRoleImpl();

		wlProjectUserRoleImpl.setGroupId(getGroupId());
		wlProjectUserRoleImpl.setCompanyId(getCompanyId());
		wlProjectUserRoleImpl.setProjectUserRoleId(getProjectUserRoleId());
		wlProjectUserRoleImpl.setProjectUserId(getProjectUserId());
		wlProjectUserRoleImpl.setRoleId(getRoleId());

		wlProjectUserRoleImpl.resetOriginalValues();

		return wlProjectUserRoleImpl;
	}

	public int compareTo(WLProjectUserRole wlProjectUserRole) {
		long primaryKey = wlProjectUserRole.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		WLProjectUserRole wlProjectUserRole = null;

		try {
			wlProjectUserRole = (WLProjectUserRole)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = wlProjectUserRole.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		WLProjectUserRoleModelImpl wlProjectUserRoleModelImpl = this;

		wlProjectUserRoleModelImpl._originalGroupId = wlProjectUserRoleModelImpl._groupId;

		wlProjectUserRoleModelImpl._setOriginalGroupId = false;

		wlProjectUserRoleModelImpl._originalCompanyId = wlProjectUserRoleModelImpl._companyId;

		wlProjectUserRoleModelImpl._setOriginalCompanyId = false;

		wlProjectUserRoleModelImpl._originalProjectUserId = wlProjectUserRoleModelImpl._projectUserId;

		wlProjectUserRoleModelImpl._setOriginalProjectUserId = false;

		wlProjectUserRoleModelImpl._originalRoleId = wlProjectUserRoleModelImpl._roleId;

		wlProjectUserRoleModelImpl._setOriginalRoleId = false;

		wlProjectUserRoleModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<WLProjectUserRole> toCacheModel() {
		WLProjectUserRoleCacheModel wlProjectUserRoleCacheModel = new WLProjectUserRoleCacheModel();

		wlProjectUserRoleCacheModel.groupId = getGroupId();

		wlProjectUserRoleCacheModel.companyId = getCompanyId();

		wlProjectUserRoleCacheModel.projectUserRoleId = getProjectUserRoleId();

		wlProjectUserRoleCacheModel.projectUserId = getProjectUserId();

		wlProjectUserRoleCacheModel.roleId = getRoleId();

		return wlProjectUserRoleCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(11);

		sb.append("{groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", projectUserRoleId=");
		sb.append(getProjectUserRoleId());
		sb.append(", projectUserId=");
		sb.append(getProjectUserId());
		sb.append(", roleId=");
		sb.append(getRoleId());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(19);

		sb.append("<model><model-name>");
		sb.append("com.jenginetest.builder.model.WLProjectUserRole");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>projectUserRoleId</column-name><column-value><![CDATA[");
		sb.append(getProjectUserRoleId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>projectUserId</column-name><column-value><![CDATA[");
		sb.append(getProjectUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>roleId</column-name><column-value><![CDATA[");
		sb.append(getRoleId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = WLProjectUserRole.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			WLProjectUserRole.class
		};
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _projectUserRoleId;
	private long _projectUserId;
	private String _projectUserUuid;
	private long _originalProjectUserId;
	private boolean _setOriginalProjectUserId;
	private long _roleId;
	private long _originalRoleId;
	private boolean _setOriginalRoleId;
	private long _columnBitmask;
	private WLProjectUserRole _escapedModelProxy;
}