/*
 * This file is part of JEngine.
 *
 * Copyright (C) 2013 Victor Burlakov
 *
 * JEngine is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * JEngine is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with JEngine.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.jenginetest.builder.model.impl;

import com.jenginetest.builder.model.WLProjectUser;
import com.jenginetest.builder.service.WLProjectUserLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the WLProjectUser service. Represents a row in the &quot;WL_WLProjectUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link WLProjectUserImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see WLProjectUserImpl
 * @see com.jenginetest.builder.model.WLProjectUser
 * @generated
 */
public abstract class WLProjectUserBaseImpl extends WLProjectUserModelImpl
	implements WLProjectUser {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a w l project user model instance should use the {@link WLProjectUser} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			WLProjectUserLocalServiceUtil.addWLProjectUser(this);
		}
		else {
			WLProjectUserLocalServiceUtil.updateWLProjectUser(this);
		}
	}
}