/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.jenginetest.builder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Member service. Represents a row in the &quot;SB_Member&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.jenginetest.builder.model.impl.MemberModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.jenginetest.builder.model.impl.MemberImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Member
 * @see com.jenginetest.builder.model.impl.MemberImpl
 * @see com.jenginetest.builder.model.impl.MemberModelImpl
 * @generated
 */
public interface MemberModel extends BaseModel<Member> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a member model instance should use the {@link Member} interface instead.
	 */

	/**
	 * Returns the primary key of this member.
	 *
	 * @return the primary key of this member
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this member.
	 *
	 * @param primaryKey the primary key of this member
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the member ID of this member.
	 *
	 * @return the member ID of this member
	 */
	public long getMemberId();

	/**
	 * Sets the member ID of this member.
	 *
	 * @param memberId the member ID of this member
	 */
	public void setMemberId(long memberId);

	/**
	 * Returns the library ID of this member.
	 *
	 * @return the library ID of this member
	 */
	public long getLibraryId();

	/**
	 * Sets the library ID of this member.
	 *
	 * @param libraryId the library ID of this member
	 */
	public void setLibraryId(long libraryId);

	/**
	 * Returns the first name of this member.
	 *
	 * @return the first name of this member
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this member.
	 *
	 * @param firstName the first name of this member
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the last name of this member.
	 *
	 * @return the last name of this member
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this member.
	 *
	 * @param lastName the last name of this member
	 */
	public void setLastName(String lastName);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Member member);

	public int hashCode();

	public CacheModel<Member> toCacheModel();

	public Member toEscapedModel();

	public String toString();

	public String toXmlString();
}