/*
 * This file is part of JEngine.
 *
 * Copyright (C) 2013 Victor Burlakov
 *
 * JEngine is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * JEngine is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with JEngine.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.jenginetest.builder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the WLEventLog service. Represents a row in the &quot;WL_WLEventLog&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.jenginetest.builder.model.impl.WLEventLogModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.jenginetest.builder.model.impl.WLEventLogImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see WLEventLog
 * @see com.jenginetest.builder.model.impl.WLEventLogImpl
 * @see com.jenginetest.builder.model.impl.WLEventLogModelImpl
 * @generated
 */
public interface WLEventLogModel extends BaseModel<WLEventLog> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a w l event log model instance should use the {@link WLEventLog} interface instead.
	 */

	/**
	 * Returns the primary key of this w l event log.
	 *
	 * @return the primary key of this w l event log
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this w l event log.
	 *
	 * @param primaryKey the primary key of this w l event log
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the group ID of this w l event log.
	 *
	 * @return the group ID of this w l event log
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this w l event log.
	 *
	 * @param groupId the group ID of this w l event log
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this w l event log.
	 *
	 * @return the company ID of this w l event log
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this w l event log.
	 *
	 * @param companyId the company ID of this w l event log
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the event log ID of this w l event log.
	 *
	 * @return the event log ID of this w l event log
	 */
	public long getEventLogId();

	/**
	 * Sets the event log ID of this w l event log.
	 *
	 * @param eventLogId the event log ID of this w l event log
	 */
	public void setEventLogId(long eventLogId);

	/**
	 * Returns the user ID of this w l event log.
	 *
	 * @return the user ID of this w l event log
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this w l event log.
	 *
	 * @param userId the user ID of this w l event log
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this w l event log.
	 *
	 * @return the user uuid of this w l event log
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this w l event log.
	 *
	 * @param userUuid the user uuid of this w l event log
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the log date of this w l event log.
	 *
	 * @return the log date of this w l event log
	 */
	public Date getLogDate();

	/**
	 * Sets the log date of this w l event log.
	 *
	 * @param logDate the log date of this w l event log
	 */
	public void setLogDate(Date logDate);

	/**
	 * Returns the event of this w l event log.
	 *
	 * @return the event of this w l event log
	 */
	@AutoEscape
	public String getEvent();

	/**
	 * Sets the event of this w l event log.
	 *
	 * @param event the event of this w l event log
	 */
	public void setEvent(String event);

	/**
	 * Returns the title of this w l event log.
	 *
	 * @return the title of this w l event log
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this w l event log.
	 *
	 * @param title the title of this w l event log
	 */
	public void setTitle(String title);

	/**
	 * Returns the model name of this w l event log.
	 *
	 * @return the model name of this w l event log
	 */
	@AutoEscape
	public String getModelName();

	/**
	 * Sets the model name of this w l event log.
	 *
	 * @param modelName the model name of this w l event log
	 */
	public void setModelName(String modelName);

	/**
	 * Returns the model p k of this w l event log.
	 *
	 * @return the model p k of this w l event log
	 */
	public Long getModelPK();

	/**
	 * Sets the model p k of this w l event log.
	 *
	 * @param modelPK the model p k of this w l event log
	 */
	public void setModelPK(Long modelPK);

	/**
	 * Returns the description of this w l event log.
	 *
	 * @return the description of this w l event log
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this w l event log.
	 *
	 * @param description the description of this w l event log
	 */
	public void setDescription(String description);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(WLEventLog wlEventLog);

	public int hashCode();

	public CacheModel<WLEventLog> toCacheModel();

	public WLEventLog toEscapedModel();

	public String toString();

	public String toXmlString();
}