/*
 * This file is part of JEngine.
 *
 * Copyright (C) 2013 Victor Burlakov
 *
 * JEngine is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * JEngine is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with JEngine.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.jenginetest.builder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the WLProject service. Represents a row in the &quot;WL_WLProject&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.jenginetest.builder.model.impl.WLProjectModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.jenginetest.builder.model.impl.WLProjectImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see WLProject
 * @see com.jenginetest.builder.model.impl.WLProjectImpl
 * @see com.jenginetest.builder.model.impl.WLProjectModelImpl
 * @generated
 */
public interface WLProjectModel extends BaseModel<WLProject> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a w l project model instance should use the {@link WLProject} interface instead.
	 */

	/**
	 * Returns the primary key of this w l project.
	 *
	 * @return the primary key of this w l project
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this w l project.
	 *
	 * @param primaryKey the primary key of this w l project
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the project ID of this w l project.
	 *
	 * @return the project ID of this w l project
	 */
	public long getProjectId();

	/**
	 * Sets the project ID of this w l project.
	 *
	 * @param projectId the project ID of this w l project
	 */
	public void setProjectId(long projectId);

	/**
	 * Returns the group ID of this w l project.
	 *
	 * @return the group ID of this w l project
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this w l project.
	 *
	 * @param groupId the group ID of this w l project
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this w l project.
	 *
	 * @return the company ID of this w l project
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this w l project.
	 *
	 * @param companyId the company ID of this w l project
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the create user ID of this w l project.
	 *
	 * @return the create user ID of this w l project
	 */
	public long getCreateUserId();

	/**
	 * Sets the create user ID of this w l project.
	 *
	 * @param createUserId the create user ID of this w l project
	 */
	public void setCreateUserId(long createUserId);

	/**
	 * Returns the create user uuid of this w l project.
	 *
	 * @return the create user uuid of this w l project
	 * @throws SystemException if a system exception occurred
	 */
	public String getCreateUserUuid() throws SystemException;

	/**
	 * Sets the create user uuid of this w l project.
	 *
	 * @param createUserUuid the create user uuid of this w l project
	 */
	public void setCreateUserUuid(String createUserUuid);

	/**
	 * Returns the create user name of this w l project.
	 *
	 * @return the create user name of this w l project
	 */
	@AutoEscape
	public String getCreateUserName();

	/**
	 * Sets the create user name of this w l project.
	 *
	 * @param createUserName the create user name of this w l project
	 */
	public void setCreateUserName(String createUserName);

	/**
	 * Returns the create date of this w l project.
	 *
	 * @return the create date of this w l project
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this w l project.
	 *
	 * @param createDate the create date of this w l project
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified user ID of this w l project.
	 *
	 * @return the modified user ID of this w l project
	 */
	public long getModifiedUserId();

	/**
	 * Sets the modified user ID of this w l project.
	 *
	 * @param modifiedUserId the modified user ID of this w l project
	 */
	public void setModifiedUserId(long modifiedUserId);

	/**
	 * Returns the modified user uuid of this w l project.
	 *
	 * @return the modified user uuid of this w l project
	 * @throws SystemException if a system exception occurred
	 */
	public String getModifiedUserUuid() throws SystemException;

	/**
	 * Sets the modified user uuid of this w l project.
	 *
	 * @param modifiedUserUuid the modified user uuid of this w l project
	 */
	public void setModifiedUserUuid(String modifiedUserUuid);

	/**
	 * Returns the modified user name of this w l project.
	 *
	 * @return the modified user name of this w l project
	 */
	@AutoEscape
	public String getModifiedUserName();

	/**
	 * Sets the modified user name of this w l project.
	 *
	 * @param modifiedUserName the modified user name of this w l project
	 */
	public void setModifiedUserName(String modifiedUserName);

	/**
	 * Returns the modified date of this w l project.
	 *
	 * @return the modified date of this w l project
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this w l project.
	 *
	 * @param modifiedDate the modified date of this w l project
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the start date of this w l project.
	 *
	 * @return the start date of this w l project
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this w l project.
	 *
	 * @param startDate the start date of this w l project
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the title of this w l project.
	 *
	 * @return the title of this w l project
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this w l project.
	 *
	 * @param title the title of this w l project
	 */
	public void setTitle(String title);

	/**
	 * Returns the status of this w l project.
	 *
	 * @return the status of this w l project
	 */
	public int getStatus();

	/**
	 * Sets the status of this w l project.
	 *
	 * @param status the status of this w l project
	 */
	public void setStatus(int status);

	/**
	 * Returns the description of this w l project.
	 *
	 * @return the description of this w l project
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this w l project.
	 *
	 * @param description the description of this w l project
	 */
	public void setDescription(String description);

	/**
	 * Returns the color of this w l project.
	 *
	 * @return the color of this w l project
	 */
	@AutoEscape
	public String getColor();

	/**
	 * Sets the color of this w l project.
	 *
	 * @param color the color of this w l project
	 */
	public void setColor(String color);

	/**
	 * Returns the lock enable of this w l project.
	 *
	 * @return the lock enable of this w l project
	 */
	public boolean getLockEnable();

	/**
	 * Returns <code>true</code> if this w l project is lock enable.
	 *
	 * @return <code>true</code> if this w l project is lock enable; <code>false</code> otherwise
	 */
	public boolean isLockEnable();

	/**
	 * Sets whether this w l project is lock enable.
	 *
	 * @param lockEnable the lock enable of this w l project
	 */
	public void setLockEnable(boolean lockEnable);

	/**
	 * Returns the lock period type of this w l project.
	 *
	 * @return the lock period type of this w l project
	 */
	@AutoEscape
	public String getLockPeriodType();

	/**
	 * Sets the lock period type of this w l project.
	 *
	 * @param lockPeriodType the lock period type of this w l project
	 */
	public void setLockPeriodType(String lockPeriodType);

	/**
	 * Returns the lock deferment of this w l project.
	 *
	 * @return the lock deferment of this w l project
	 */
	public int getLockDeferment();

	/**
	 * Sets the lock deferment of this w l project.
	 *
	 * @param lockDeferment the lock deferment of this w l project
	 */
	public void setLockDeferment(int lockDeferment);

	/**
	 * Returns the automatically assign of this w l project.
	 *
	 * @return the automatically assign of this w l project
	 */
	public boolean getAutomaticallyAssign();

	/**
	 * Returns <code>true</code> if this w l project is automatically assign.
	 *
	 * @return <code>true</code> if this w l project is automatically assign; <code>false</code> otherwise
	 */
	public boolean isAutomaticallyAssign();

	/**
	 * Sets whether this w l project is automatically assign.
	 *
	 * @param automaticallyAssign the automatically assign of this w l project
	 */
	public void setAutomaticallyAssign(boolean automaticallyAssign);

	/**
	 * Returns the default project of this w l project.
	 *
	 * @return the default project of this w l project
	 */
	public boolean getDefaultProject();

	/**
	 * Returns <code>true</code> if this w l project is default project.
	 *
	 * @return <code>true</code> if this w l project is default project; <code>false</code> otherwise
	 */
	public boolean isDefaultProject();

	/**
	 * Sets whether this w l project is default project.
	 *
	 * @param defaultProject the default project of this w l project
	 */
	public void setDefaultProject(boolean defaultProject);

	/**
	 * Returns the external url of this w l project.
	 *
	 * @return the external url of this w l project
	 */
	@AutoEscape
	public String getExternalUrl();

	/**
	 * Sets the external url of this w l project.
	 *
	 * @param externalUrl the external url of this w l project
	 */
	public void setExternalUrl(String externalUrl);

	/**
	 * Returns the external mandatory of this w l project.
	 *
	 * @return the external mandatory of this w l project
	 */
	public boolean getExternalMandatory();

	/**
	 * Returns <code>true</code> if this w l project is external mandatory.
	 *
	 * @return <code>true</code> if this w l project is external mandatory; <code>false</code> otherwise
	 */
	public boolean isExternalMandatory();

	/**
	 * Sets whether this w l project is external mandatory.
	 *
	 * @param externalMandatory the external mandatory of this w l project
	 */
	public void setExternalMandatory(boolean externalMandatory);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(WLProject wlProject);

	public int hashCode();

	public CacheModel<WLProject> toCacheModel();

	public WLProject toEscapedModel();

	public String toString();

	public String toXmlString();
}