/*
 * This file is part of JEngine.
 *
 * Copyright (C) 2013 Victor Burlakov
 *
 * JEngine is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * JEngine is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with JEngine.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.jenginetest.builder.model;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the WLProjectUserRole service. Represents a row in the &quot;WL_WLProjectUserRole&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.jenginetest.builder.model.impl.WLProjectUserRoleModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.jenginetest.builder.model.impl.WLProjectUserRoleImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see WLProjectUserRole
 * @see com.jenginetest.builder.model.impl.WLProjectUserRoleImpl
 * @see com.jenginetest.builder.model.impl.WLProjectUserRoleModelImpl
 * @generated
 */
public interface WLProjectUserRoleModel extends BaseModel<WLProjectUserRole> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a w l project user role model instance should use the {@link WLProjectUserRole} interface instead.
	 */

	/**
	 * Returns the primary key of this w l project user role.
	 *
	 * @return the primary key of this w l project user role
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this w l project user role.
	 *
	 * @param primaryKey the primary key of this w l project user role
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the group ID of this w l project user role.
	 *
	 * @return the group ID of this w l project user role
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this w l project user role.
	 *
	 * @param groupId the group ID of this w l project user role
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this w l project user role.
	 *
	 * @return the company ID of this w l project user role
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this w l project user role.
	 *
	 * @param companyId the company ID of this w l project user role
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the project user role ID of this w l project user role.
	 *
	 * @return the project user role ID of this w l project user role
	 */
	public long getProjectUserRoleId();

	/**
	 * Sets the project user role ID of this w l project user role.
	 *
	 * @param projectUserRoleId the project user role ID of this w l project user role
	 */
	public void setProjectUserRoleId(long projectUserRoleId);

	/**
	 * Returns the project user ID of this w l project user role.
	 *
	 * @return the project user ID of this w l project user role
	 */
	public long getProjectUserId();

	/**
	 * Sets the project user ID of this w l project user role.
	 *
	 * @param projectUserId the project user ID of this w l project user role
	 */
	public void setProjectUserId(long projectUserId);

	/**
	 * Returns the project user uuid of this w l project user role.
	 *
	 * @return the project user uuid of this w l project user role
	 * @throws SystemException if a system exception occurred
	 */
	public String getProjectUserUuid() throws SystemException;

	/**
	 * Sets the project user uuid of this w l project user role.
	 *
	 * @param projectUserUuid the project user uuid of this w l project user role
	 */
	public void setProjectUserUuid(String projectUserUuid);

	/**
	 * Returns the role ID of this w l project user role.
	 *
	 * @return the role ID of this w l project user role
	 */
	public long getRoleId();

	/**
	 * Sets the role ID of this w l project user role.
	 *
	 * @param roleId the role ID of this w l project user role
	 */
	public void setRoleId(long roleId);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(WLProjectUserRole wlProjectUserRole);

	public int hashCode();

	public CacheModel<WLProjectUserRole> toCacheModel();

	public WLProjectUserRole toEscapedModel();

	public String toString();

	public String toXmlString();
}