/*
 * This file is part of JEngine.
 *
 * Copyright (C) 2013 Victor Burlakov
 *
 * JEngine is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * JEngine is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with JEngine.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.jenginetest.builder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the WLTask service. Represents a row in the &quot;WL_WLTask&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.jenginetest.builder.model.impl.WLTaskModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.jenginetest.builder.model.impl.WLTaskImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see WLTask
 * @see com.jenginetest.builder.model.impl.WLTaskImpl
 * @see com.jenginetest.builder.model.impl.WLTaskModelImpl
 * @generated
 */
public interface WLTaskModel extends BaseModel<WLTask> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a w l task model instance should use the {@link WLTask} interface instead.
	 */

	/**
	 * Returns the primary key of this w l task.
	 *
	 * @return the primary key of this w l task
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this w l task.
	 *
	 * @param primaryKey the primary key of this w l task
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the task ID of this w l task.
	 *
	 * @return the task ID of this w l task
	 */
	public long getTaskId();

	/**
	 * Sets the task ID of this w l task.
	 *
	 * @param taskId the task ID of this w l task
	 */
	public void setTaskId(long taskId);

	/**
	 * Returns the group ID of this w l task.
	 *
	 * @return the group ID of this w l task
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this w l task.
	 *
	 * @param groupId the group ID of this w l task
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this w l task.
	 *
	 * @return the company ID of this w l task
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this w l task.
	 *
	 * @param companyId the company ID of this w l task
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the create user ID of this w l task.
	 *
	 * @return the create user ID of this w l task
	 */
	public long getCreateUserId();

	/**
	 * Sets the create user ID of this w l task.
	 *
	 * @param createUserId the create user ID of this w l task
	 */
	public void setCreateUserId(long createUserId);

	/**
	 * Returns the create user uuid of this w l task.
	 *
	 * @return the create user uuid of this w l task
	 * @throws SystemException if a system exception occurred
	 */
	public String getCreateUserUuid() throws SystemException;

	/**
	 * Sets the create user uuid of this w l task.
	 *
	 * @param createUserUuid the create user uuid of this w l task
	 */
	public void setCreateUserUuid(String createUserUuid);

	/**
	 * Returns the create user name of this w l task.
	 *
	 * @return the create user name of this w l task
	 */
	@AutoEscape
	public String getCreateUserName();

	/**
	 * Sets the create user name of this w l task.
	 *
	 * @param createUserName the create user name of this w l task
	 */
	public void setCreateUserName(String createUserName);

	/**
	 * Returns the create date of this w l task.
	 *
	 * @return the create date of this w l task
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this w l task.
	 *
	 * @param createDate the create date of this w l task
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified user ID of this w l task.
	 *
	 * @return the modified user ID of this w l task
	 */
	public long getModifiedUserId();

	/**
	 * Sets the modified user ID of this w l task.
	 *
	 * @param modifiedUserId the modified user ID of this w l task
	 */
	public void setModifiedUserId(long modifiedUserId);

	/**
	 * Returns the modified user uuid of this w l task.
	 *
	 * @return the modified user uuid of this w l task
	 * @throws SystemException if a system exception occurred
	 */
	public String getModifiedUserUuid() throws SystemException;

	/**
	 * Sets the modified user uuid of this w l task.
	 *
	 * @param modifiedUserUuid the modified user uuid of this w l task
	 */
	public void setModifiedUserUuid(String modifiedUserUuid);

	/**
	 * Returns the modified user name of this w l task.
	 *
	 * @return the modified user name of this w l task
	 */
	@AutoEscape
	public String getModifiedUserName();

	/**
	 * Sets the modified user name of this w l task.
	 *
	 * @param modifiedUserName the modified user name of this w l task
	 */
	public void setModifiedUserName(String modifiedUserName);

	/**
	 * Returns the modified date of this w l task.
	 *
	 * @return the modified date of this w l task
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this w l task.
	 *
	 * @param modifiedDate the modified date of this w l task
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the subject of this w l task.
	 *
	 * @return the subject of this w l task
	 */
	@AutoEscape
	public String getSubject();

	/**
	 * Sets the subject of this w l task.
	 *
	 * @param subject the subject of this w l task
	 */
	public void setSubject(String subject);

	/**
	 * Returns the project ID of this w l task.
	 *
	 * @return the project ID of this w l task
	 */
	public long getProjectId();

	/**
	 * Sets the project ID of this w l task.
	 *
	 * @param projectId the project ID of this w l task
	 */
	public void setProjectId(long projectId);

	/**
	 * Returns the owner ID of this w l task.
	 *
	 * @return the owner ID of this w l task
	 */
	public long getOwnerId();

	/**
	 * Sets the owner ID of this w l task.
	 *
	 * @param ownerId the owner ID of this w l task
	 */
	public void setOwnerId(long ownerId);

	/**
	 * Returns the worker ID of this w l task.
	 *
	 * @return the worker ID of this w l task
	 */
	public long getWorkerId();

	/**
	 * Sets the worker ID of this w l task.
	 *
	 * @param workerId the worker ID of this w l task
	 */
	public void setWorkerId(long workerId);

	/**
	 * Returns the external ID of this w l task.
	 *
	 * @return the external ID of this w l task
	 */
	@AutoEscape
	public String getExternalId();

	/**
	 * Sets the external ID of this w l task.
	 *
	 * @param externalId the external ID of this w l task
	 */
	public void setExternalId(String externalId);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(WLTask wlTask);

	public int hashCode();

	public CacheModel<WLTask> toCacheModel();

	public WLTask toEscapedModel();

	public String toString();

	public String toXmlString();
}